name: Build & Test API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # InvisiRisk: Setup PSE
    - name: Setup PSE
      uses: invisirisk/pse-action@v1.0.20
      with:
        api_url: "https://app.invisirisk.com"
        app_token: ${{ secrets.IR_API_KEY }}

    # Checkout repository
    - uses: actions/checkout@v3

    # Setup Node.js
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - run: npm ci

    # Run tests
    - run: npm test

    # InvisiRisk: Cleanup PSE
    - name: Cleanup PSE
      if: always()
      uses: invisirisk/pse-action@v1.0.20
      with:
        cleanup: "true"
